[package]
name = "log-revolve-rs"
version = "0.1.0"
authors = ["Denis Novozhilov <cartoonraccoon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6"
structopt = "0.3"
chrono = "0.4"